<?php
/**
 * QuestionTest
 *
 * PHP version 7
 *
 * @category Class
 * @package CollingMedia\Lasso
 * @author   Brian Logan
 * @link     https://github.com/colling-media/lasso-api
 */

/**
 * Lasso API
 *
 * Manage Registrant and Inventory data within Lasso CRM.  Authorization header with a Bearer JWT api key token is required for all requests. API keys are project/location based, and can be obtained from your business contact with Lasso Data Systems. In the future, Project Admin's will be able to generate their own api keys from the Lasso CRM web application.  To try it out in swagger: - Select the `Authorize` button and place your api key in the textbox - Ensure that the api key is prefixed with `Bearer` including a space separating `Bearer` from the api key - Go to the route you want to try out in the swagger definition - Select `Try it out` - Input any required fields, query params, and request payload - Select `Execute`  Alternatively, you can try it on your command line with curl, for example: `curl -X GET \"https://api.lassocrm.com/v1/registrants/123456\" -H \"accept: application/json\" -H \"Authorization: Bearer ***apikey***\"`
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */


namespace CollingMedia\Lasso;

use PHPUnit\Framework\TestCase;
/**
 * QuestionTest Class Doc Comment
 *
 * @category    Class
 * @description Questions in Lasso are sorted into folders. You can use &#x60;path&#x60; to specify which folder the question should be saved to.  Specifying the questionId will override name and path and the question will be looked up by its ID. If no question is found the question is *not* created and the request fails.  Any existing registrant answers to the question will be replaced by the answers from this request. Existing answer options on the question will not be removed.  If the question does not exist and no question ID is provided, a new question will be created. If the path is empty, the question will be created in a folder named after the API key vendor type - ie, &#x60;lassoLeadCapture&#x60;.  The possible answer options are created for each answer provided in the &#x60;answer&#x60; key. Only question type &#x60;checkbox&#x60; supports multiple answers. All of them will be marked as checked for the registrant.
 * @package     CollingMedia\Lasso
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class QuestionTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Question"
     */
    public function testQuestion()
    {
    }

    /**
     * Test attribute "question_id"
     */
    public function testPropertyQuestionId()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "path"
     */
    public function testPropertyPath()
    {
    }

    /**
     * Test attribute "answers"
     */
    public function testPropertyAnswers()
    {
    }
}
