<?php
/**
 * SalesRepTest.
 *
 * PHP version 7
 *
 * @category Class
 * @author   Brian Logan
 * @link     https://github.com/colling-media/lasso-api
 */

/**
 * Lasso API.
 *
 * Manage Registrant and Inventory data within Lasso CRM.  Authorization header with a Bearer JWT api key token is required for all requests. API keys are project/location based, and can be obtained from your business contact with Lasso Data Systems. In the future, Project Admin's will be able to generate their own api keys from the Lasso CRM web application.  To try it out in swagger: - Select the `Authorize` button and place your api key in the textbox - Ensure that the api key is prefixed with `Bearer` including a space separating `Bearer` from the api key - Go to the route you want to try out in the swagger definition - Select `Try it out` - Input any required fields, query params, and request payload - Select `Execute`  Alternatively, you can try it on your command line with curl, for example: `curl -X GET \"https://api.lassocrm.com/v1/registrants/123456\" -H \"accept: application/json\" -H \"Authorization: Bearer ***apikey***\"`
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace CollingMedia\Lasso;

use PHPUnit\Framework\TestCase;

/**
 * SalesRepTest Class Doc Comment.
 *
 * @category    Class
 * @description When inputting a salesRep, you can provide a userId and the system will try to look up the salesRep by the ID.  If no userId is provided but a first and last name are, then the system will lookup the salesRep by name and assign it to this registrant.  Otherwise, no salesRep will be assigned.  Notes: - if multiple salesReps are being assigned, take care to only   choose one to be primary. If multiple are designated as primary, an error will   be returned - on registrant create, if both rotationId and assignedSalesReps are specified,   assignedSalesReps will override rotationId in salesRep selection.
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SalesRepTest extends TestCase
{
    /**
     * Setup before running any test case.
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case.
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case.
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases.
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "SalesRep".
     */
    public function testSalesRep()
    {
    }

    /**
     * Test attribute "user_id".
     */
    public function testPropertyUserId()
    {
    }

    /**
     * Test attribute "first_name".
     */
    public function testPropertyFirstName()
    {
    }

    /**
     * Test attribute "last_name".
     */
    public function testPropertyLastName()
    {
    }

    /**
     * Test attribute "is_primary".
     */
    public function testPropertyIsPrimary()
    {
    }
}
